name: Deploy

on:
  push:
    branches: [ main ]

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true      

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "alessandrocandolini-heroku-mvp" #Must be unique in Heroku
          heroku_email: "alessandro.candolini@gmail.com"
          usedocker: true
          healthcheck: "https://[YOUR APP's NAME].herokuapp.com/status"
          delay: 5
          rollbackonhealthcheckfailed: true
