name: Scala CI

on:
  push:
    branches: [ main, 'feature/*' ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        scala: [3.1.0]
    runs-on: ubuntu-latest

    steps:

      - name: Checkout current branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
            ~/AppData/Local/Coursier/Cache/v1
            ~/Library/Caches/Coursier/v1
          key: sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - name: Build project
        run: sbt ++${{ matrix.scala }} clean assembly

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "alessandrocandolini-heroku-mvp"
          heroku_email: "alessandro.candolini@gmail.com"
          usedocker: true
          healthcheck: "https://alessandrocandolini-heroku-mvp.herokuapp.com/status"
          delay: 5
          rollbackonhealthcheckfailed: true

      - name: Tag release
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "latest $(date -u +'%Y%m%d%H%M%SZ')"

      - name: Create Github Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          files: target/scala-3.1.0/heroku-mvp.jar
